<?php

namespace Database\Seeders;

use App\Models\Vehicle;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class VehicleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $vehicles = [
            [
                'make' => 'Toyota',
                'model' => 'Camry',
                'year' => 2023,
                'color' => 'Silver',
                'price' => 1299000.00,
                'stock' => 5,
                'description' => 'รถยนต์ซีดานขนาดกลางที่มีประสิทธิภาพการใช้น้ำมันที่ดี',
            ],
            [
                'make' => 'Honda',
                'model' => 'CR-V',
                'year' => 2024,
                'color' => 'Blue',
                'price' => 1459000.00,
                'stock' => 3,
                'description' => 'รถ SUV ขนาดกะทัดรัดพร้อมระบบความปลอดภัยขั้นสูง',
            ],
            [
                'make' => 'Ford',
                'model' => 'Ranger',
                'year' => 2023,
                'color' => 'Black',
                'price' => 999000.00,
                'stock' => 4,
                'description' => 'กระบะที่มีประสิทธิภาพสูงพร้อมตัวเลือกเครื่องยนต์ที่ทรงพลัง',
            ],
            [
                'make' => 'MG',
                'model' => 'ZS EV',
                'year' => 2024,
                'color' => 'White',
                'price' => 1179000.00,
                'stock' => 2,
                'description' => 'รถยนต์ไฟฟ้า SUV ที่ทันสมัยพร้อมเทคโนโลยีล้ำสมัย',
            ],
            [
                'make' => 'BMW',
                'model' => 'X5',
                'year' => 2023,
                'color' => 'Gray',
                'price' => 4999000.00,
                'stock' => 3,
                'description' => 'รถ SUV หรูพร้อมคุณสมบัติระดับพรีเมียม',
            ],
            [
                'make' => 'Isuzu',
                'model' => 'D-Max',
                'year' => 2024,
                'color' => 'Red',
                'price' => 869000.00,
                'stock' => 6,
                'description' => 'กระบะที่แข็งแกร่งและประหยัดน้ำมัน',
            ],
            [
                'make' => 'Mercedes-Benz',
                'model' => 'C-Class',
                'year' => 2023,
                'color' => 'Black',
                'price' => 2899000.00,
                'stock' => 2,
                'description' => 'รถซีดานหรูพร้อมเทคโนโลยีล้ำสมัย',
            ],
            [
                'make' => 'Mazda',
                'model' => 'CX-5',
                'year' => 2024,
                'color' => 'Soul Red Crystal',
                'price' => 1359000.00,
                'stock' => 4,
                'description' => 'ครอสโอเวอร์ SUV สไตล์สปอร์ตหรูหรา',
            ],
            [
                'make' => 'Nissan',
                'model' => 'Kicks e-POWER',
                'year' => 2023,
                'color' => 'Blue',
                'price' => 989000.00,
                'stock' => 3,
                'description' => 'รถครอสโอเวอร์ไฮบริดประหยัดพลังงาน',
            ],
            [
                'make' => 'Mitsubishi',
                'model' => 'Pajero Sport',
                'year' => 2024,
                'color' => 'White Diamond',
                'price' => 1459000.00,
                'stock' => 2,
                'description' => 'รถ PPV สมรรถนะสูงเหมาะสำหรับทุกการใช้งาน',
            ],
            // เพิ่มข้อมูลรถยนต์อีก 20 รายการ
            [
                'make' => 'Toyota',
                'model' => 'Fortuner',
                'year' => 2024,
                'color' => 'Phantom Brown',
                'price' => 1659000.00,
                'stock' => 3,
                'description' => 'รถ PPV สมรรถนะสูงเหมาะกับทุกเส้นทาง',
            ],
            [
                'make' => 'Honda',
                'model' => 'City',
                'year' => 2023,
                'color' => 'Platinum White Pearl',
                'price' => 749000.00,
                'stock' => 5,
                'description' => 'รถซีดานขนาดเล็กประหยัดน้ำมัน',
            ],
            [
                'make' => 'Mazda',
                'model' => '3',
                'year' => 2024,
                'color' => 'Machine Gray',
                'price' => 1069000.00,
                'stock' => 4,
                'description' => 'รถซีดานสปอร์ตดีไซน์หรูหรา',
            ],
            [
                'make' => 'Toyota',
                'model' => 'Yaris',
                'year' => 2023,
                'color' => 'Super Red',
                'price' => 549000.00,
                'stock' => 6,
                'description' => 'รถแฮทช์แบ็คขนาดเล็กคล่องตัวในเมือง',
            ],
            [
                'make' => 'MG',
                'model' => 'HS',
                'year' => 2024,
                'color' => 'Black Knight',
                'price' => 979000.00,
                'stock' => 3,
                'description' => 'รถ SUV ขนาดกลางพร้อมเทคโนโลยีทันสมัย',
            ],
            [
                'make' => 'BMW',
                'model' => '3 Series',
                'year' => 2023,
                'color' => 'Mineral Gray',
                'price' => 2599000.00,
                'stock' => 2,
                'description' => 'รถซีดานหรูสมรรถนะสูง',
            ],
            [
                'make' => 'Mercedes-Benz',
                'model' => 'GLC',
                'year' => 2024,
                'color' => 'Obsidian Black',
                'price' => 3899000.00,
                'stock' => 2,
                'description' => 'รถ SUV หรูระดับพรีเมียม',
            ],
            [
                'make' => 'Volvo',
                'model' => 'XC40',
                'year' => 2023,
                'color' => 'Crystal White',
                'price' => 2199000.00,
                'stock' => 3,
                'description' => 'รถ SUV ขนาดเล็กพร้อมระบบความปลอดภัยระดับสูง',
            ],
            [
                'make' => 'Audi',
                'model' => 'Q5',
                'year' => 2024,
                'color' => 'Manhattan Gray',
                'price' => 3599000.00,
                'stock' => 2,
                'description' => 'รถ SUV หรูสมรรถนะสูง',
            ],
            [
                'make' => 'Lexus',
                'model' => 'ES',
                'year' => 2023,
                'color' => 'Sonic Titanium',
                'price' => 3699000.00,
                'stock' => 2,
                'description' => 'รถซีดานหรูระดับพรีเมียม',
            ],
            [
                'make' => 'Subaru',
                'model' => 'Forester',
                'year' => 2024,
                'color' => 'Horizon Blue',
                'price' => 1599000.00,
                'stock' => 3,
                'description' => 'รถ SUV ขับเคลื่อนสี่ล้อสมรรถนะสูง',
            ],
            [
                'make' => 'Porsche',
                'model' => 'Macan',
                'year' => 2023,
                'color' => 'Carrara White',
                'price' => 5199000.00,
                'stock' => 1,
                'description' => 'รถ SUV สปอร์ตสมรรถนะสูง',
            ],
            [
                'make' => 'Toyota',
                'model' => 'Corolla Cross',
                'year' => 2024,
                'color' => 'Metal Stream',
                'price' => 1089000.00,
                'stock' => 4,
                'description' => 'ครอสโอเวอร์ SUV ประหยัดน้ำมัน',
            ],
            [
                'make' => 'Honda',
                'model' => 'Civic',
                'year' => 2023,
                'color' => 'Sonic Gray',
                'price' => 1149000.00,
                'stock' => 3,
                'description' => 'รถซีดานสปอร์ตสมรรถนะสูง',
            ],
            [
                'make' => 'Nissan',
                'model' => 'Terra',
                'year' => 2024,
                'color' => 'Brilliant Silver',
                'price' => 1399000.00,
                'stock' => 2,
                'description' => 'รถ PPV สมรรถนะสูงพร้อมลุยทุกเส้นทาง',
            ],
            [
                'make' => 'Ford',
                'model' => 'Everest',
                'year' => 2023,
                'color' => 'Arctic White',
                'price' => 1599000.00,
                'stock' => 3,
                'description' => 'รถ SUV อเนกประสงค์สมรรถนะสูง',
            ],
            [
                'make' => 'MG',
                'model' => '4',
                'year' => 2024,
                'color' => 'Brighton Blue',
                'price' => 869000.00,
                'stock' => 4,
                'description' => 'รถยนต์ไฟฟ้าแฮทช์แบ็คประหยัดพลังงาน',
            ],
            [
                'make' => 'Hyundai',
                'model' => 'IONIQ 5',
                'year' => 2023,
                'color' => 'Atlas White',
                'price' => 1899000.00,
                'stock' => 2,
                'description' => 'รถยนต์ไฟฟ้า SUV นวัตกรรมล้ำสมัย',
            ],
            [
                'make' => 'Kia',
                'model' => 'Carnival',
                'year' => 2024,
                'color' => 'Astra Blue',
                'price' => 2199000.00,
                'stock' => 2,
                'description' => 'รถ MPV หรูหราเหมาะสำหรับครอบครัว',
            ],
            [
                'make' => 'Suzuki',
                'model' => 'Swift',
                'year' => 2023,
                'color' => 'Burning Red',
                'price' => 549000.00,
                'stock' => 5,
                'description' => 'รถแฮทช์แบ็คขนาดเล็กประหยัดน้ำมัน',
            ],
        ];

        foreach ($vehicles as $vehicle) {
            Vehicle::create($vehicle);
        }
    }
}
